ALTER TABLE Users ALTER COLUMN profile_uri SET NOT NULL;
ALTER TABLE Users ALTER COLUMN photo_uri SET NOT NULL;

ALTER TABLE Organizations ALTER COLUMN fk_user DROP NOT NULL;
ALTER TABLE Individuals ALTER COLUMN fk_user DROP NOT NULL;
