ALTER TABLE Users ALTER COLUMN profile_uri DROP NOT NULL;
ALTER TABLE Users ALTER COLUMN photo_uri DROP NOT NULL;

ALTER TABLE Organizations ALTER COLUMN fk_user SET NOT NULL;
ALTER TABLE Individuals ALTER COLUMN fk_user SET NOT NULL;
